(autoload 'furl--get-boundary                   "furl" "" nil)
(autoload 'furl--handle-errors                  "furl" "" nil)
(autoload 'furl--make-query-string              "furl" "" nil)
(autoload 'furl--make-multipart-data            "furl" "" nil)
(autoload 'furl--get-response-body              "furl" "" nil)
(autoload 'furl-with-header                     "furl" "" nil 'macro)
(autoload 'furl--wrap-request                   "furl" "" nil 'macro)
(autoload 'furl-retrieve                        "furl" "" nil)
(autoload 'furl-retrieve-synchronously          "furl" "" nil)
(provide 'lib-furl-epackage-autoloads)
